import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:image_picker/image_picker.dart';
import 'package:leaptech_plus/core/services/supabase_service.dart';
import 'package:leaptech_plus/core/themes/app_colors.dart';
import 'package:leaptech_plus/core/utils/spacing.dart';
import 'package:leaptech_plus/core/widgets/app_button.dart';
import 'package:leaptech_plus/core/widgets/app_text_form_field.dart';
import 'package:leaptech_plus/features/login/data/models/user_model.dart';

class EmployeeFormSheet extends StatefulWidget {
  final UserModel? employee;
  final Function(UserModel) onSave;

  const EmployeeFormSheet({
    super.key,
    this.employee,
    required this.onSave,
  });

  @override
  State<EmployeeFormSheet> createState() => _EmployeeFormSheetState();
}

class _EmployeeFormSheetState extends State<EmployeeFormSheet> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _fullNameController = TextEditingController();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _phoneController = TextEditingController();
  final TextEditingController _branchController = TextEditingController();

  String? _selectedType;
  String? _imageUrl;
  File? _imageFile;
  final ImagePicker _picker = ImagePicker();

  final List<String> _employeeTypes = ['Admin', 'Employee', 'Internship'];

  bool get isEditing => widget.employee != null;

  @override
  void initState() {
    super.initState();
    if (isEditing) {
      _fullNameController.text = widget.employee!.fullName;
      _emailController.text = widget.employee!.email;
      _titleController.text = widget.employee!.title;
      _selectedType = widget.employee!.type;
      _phoneController.text = widget.employee!.phone ?? '';
      _branchController.text = widget.employee!.branch ?? '';
      _imageUrl = widget.employee!.imageUrl;
    } else {
      // Set default type for new employees
      _selectedType = _employeeTypes[1]; // Default to 'Employee'
    }
  }

  @override
  void dispose() {
    _fullNameController.dispose();
    _emailController.dispose();
    _passwordController.dispose();
    _titleController.dispose();
    _phoneController.dispose();
    _branchController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    try {
      final XFile? pickedFile = await _picker.pickImage(
        source: ImageSource.gallery,
      );

      if (pickedFile != null) {
        setState(() {
          _imageFile = File(pickedFile.path);
        });

        try {
          // Upload image to Supabase
          final supabaseService = SupabaseService();
          final String uploadedUrl = await supabaseService.uploadImage(
            file: _imageFile!,
            folder: 'employee_images',
          );

          setState(() {
            _imageUrl = uploadedUrl;
            _imageFile = null; // Clear the file after successful upload
          });
        } catch (e) {
          setState(() {
            _imageFile = null; // Clear the file on error
          });
          if (context.mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Error uploading image: $e')),
            );
          }
        }
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error picking image: $e')),
        );
      }
    }
  }

  void _saveEmployee() {
    if (_formKey.currentState!.validate() && _selectedType != null) {
      if (isEditing) {
        // Update existing employee
        final updatedEmployee = UserModel(
          id: widget.employee!.id,
          fullName: _fullNameController.text,
          email: _emailController.text,
          password: '', // Password is not updated in edit mode
          title: _titleController.text,
          type: _selectedType!,
          phone: _phoneController.text.isEmpty ? null : _phoneController.text,
          branch:
              _branchController.text.isEmpty ? null : _branchController.text,
          imageUrl: _imageUrl,
        );
        widget.onSave(updatedEmployee);
      } else {
        // Add new employee
        final newEmployee = UserModel(
          id: '', // Will be generated by backend
          fullName: _fullNameController.text,
          email: _emailController.text,
          password: _passwordController.text,
          title: _titleController.text,
          type: _selectedType!,
          phone: _phoneController.text.isEmpty ? null : _phoneController.text,
          branch:
              _branchController.text.isEmpty ? null : _branchController.text,
          imageUrl: _imageUrl,
        );
        widget.onSave(newEmployee);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.only(top: 50.h),
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
        left: 20,
        right: 20,
        top: 20,
      ),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  isEditing ? 'Edit Employee' : 'Add New Employee',
                  style: const TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                    color: Colors.black87,
                  ),
                ),
                IconButton(
                  onPressed: () => Navigator.of(context).pop(),
                  icon: const Icon(Icons.close, color: Colors.black54),
                ),
              ],
            ),
            verticalSpace(20),
            Center(
              child: GestureDetector(
                onTap: _pickImage,
                child: CircleAvatar(
                  radius: 50,
                  backgroundColor: Colors.grey[200],
                  backgroundImage: _imageUrl != null
                      ? NetworkImage(_imageUrl!) as ImageProvider<Object>?
                      : _imageFile != null
                          ? FileImage(_imageFile!) as ImageProvider<Object>?
                          : null,
                  child: _imageUrl == null && _imageFile == null
                      ? const Icon(Icons.camera_alt,
                          size: 40, color: Colors.grey)
                      : null,
                ),
              ),
            ),
            verticalSpace(20),
            Form(
              key: _formKey,
              child: Column(
                children: [
                  AppTextFormField(
                    controller: _fullNameController,
                    hintText: 'Full Name',
                    labelText: 'Full Name',
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter full name';
                      }
                      return null;
                    },
                  ),
                  verticalSpace(15),
                  AppTextFormField(
                    controller: _emailController,
                    hintText: 'Email',
                    labelText: 'Email',
                    keyboardType: TextInputType.emailAddress,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter email';
                      }
                      if (!RegExp(r'^[^@]+@[^@]+\.[^@]+').hasMatch(value)) {
                        return 'Please enter a valid email';
                      }
                      return null;
                    },
                  ),
                  verticalSpace(15),
                  if (!isEditing)
                    AppTextFormField(
                      controller: _passwordController,
                      hintText: 'Password',
                      labelText: 'Password',
                      obscureText: false,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter password';
                        }
                        if (value.length < 6) {
                          return 'Password must be at least 6 characters';
                        }
                        return null;
                      },
                    ),
                  if (!isEditing) verticalSpace(15),
                  AppTextFormField(
                    controller: _titleController,
                    hintText: 'Title',
                    labelText: 'Title',
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter title';
                      }
                      return null;
                    },
                  ),
                  verticalSpace(15),
                  // Dropdown for employee type
                  DropdownButtonFormField<String>(
                    value: _selectedType,
                    hint: const Text('Select Type'),
                    items: _employeeTypes.map((String type) {
                      return DropdownMenuItem<String>(
                        value: type,
                        child: Text(type),
                      );
                    }).toList(),
                    onChanged: (String? newValue) {
                      setState(() {
                        _selectedType = newValue;
                      });
                    },
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please select a type';
                      }
                      return null;
                    },
                    decoration: InputDecoration(
                      contentPadding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 16,
                      ),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: BorderSide(color: Colors.grey[300]!),
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: const BorderSide(
                          color: AppColors.primaryColor,
                          width: 2,
                        ),
                      ),
                    ),
                  ),
                  verticalSpace(15),
                  AppTextFormField(
                    controller: _phoneController,
                    hintText: 'Phone (optional)',
                    labelText: 'Phone (optional)',
                    keyboardType: TextInputType.phone,
                  ),
                  verticalSpace(15),
                  AppTextFormField(
                    controller: _branchController,
                    hintText: 'Branch (optional)',
                    labelText: 'Branch (optional)',
                  ),
                  verticalSpace(20),
                  Row(
                    children: [
                      Expanded(
                        child: AppButton(
                          buttonText: 'Cancel',
                          onPressed: () => Navigator.of(context).pop(),
                          backgroundColor: Colors.grey[300]!,
                          textColor: Colors.black87,
                        ),
                      ),
                      horizontalSpace(15),
                      Expanded(
                        child: AppButton(
                          buttonText: isEditing ? 'Update' : 'Add',
                          onPressed: _saveEmployee,
                          backgroundColor: AppColors.primaryColor,
                        ),
                      ),
                    ],
                  ),
                  verticalSpace(20),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
